# Fetching config from server at : http://localhost:8083
spring:
  application:
    name: user-service
  cloud:
    config:
      uri: http://localhost:8083
  config:
    import: optional:configserver:http://localhost:8083  

# Connection url for our DB
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrival=true
# User and password to login
    username: root
    password: root03
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
# Show error message
server:
  error:
    include-message: always